### ISSUE TITLE
Text Changes 

### ISSUE THREAD

**Issue by rameshelamathi** [wployalty/wployalty_judge_me#6]
WPLoyalty - Judge.me Compatibility => WPLoyalty - Judge.Me

WPLoyalty - Judge.me Compatibility (plugin description) - The add-on integrates WPLoyalty with the Judge.me and allows you to reward customers with points for writing reviews in Judge.me

WebHooks 
(Add the following description)

NOTE: You should have set up the Jofficial udge.me for WooCommerce plugin properly before attempting to create the webhooks. This add-on depends on the configuration from the official Judge.me plugin for WooCommerce.

Please click on the "Create" button to create a Webhook in your Judge.me account so that when a review is posted, WPloyalty can listen and reward the customer with points / rewards as per your configuration.

WebHook id => Webhook ID
WebHook key => Webhook Key
WebHook url => Webhook URL

**Comment by Mercypaul27** [comment]
Fixed
Text changed in the initial release
![image](https://github.com/user-attachments/assets/72af4b7b-90c6-4305-93c8-51e572c4f0b7)
